### ISSUE TITLE
Update pngjs v3.3.0

### ISSUE THREAD

**Issue by b-long** [kevva/parse-png#1]
NB: pngjs v3.3.0 has been released -> https://github.com/lukeapage/pngjs/commits/master

Mind updating [your dependency](https://github.com/kevva/parse-png/blob/9ae868b40c65b6da37005c165ee9de2cc0ff26fe/package.json#L26-L28) and re-releasing this, https://github.com/kevva/to-ico, and https://github.com/kevva/to-ico-cli ? 

Thanks for your work! 👍

**Comment by kevva** [comment]
It should use `3.3.0` already since it's prefixed with a caret which will resolve the latest minor version.
